### ISSUE TITLE
Switch from `pandas` to `polars` for more efficient downstream tasks, e.g. faster queries

### ISSUE THREAD

**Issue by abearab** [BiocPy/BiocFrame#107]
Thanks for developing all amazing BiocPy tools! As I just mentioned in https://github.com/BiocPy/GenomicRanges/issues/84, I think there are more efficient backends to be used here. Looking forward to hear thoughts.

**Comment by jkanche** [comment]
Thank you posting this, I was thinking of this at some point (https://github.com/BiocPy/BiocFrame/issues/5). might be a good time to revisit this issue.

I believe it comes down to supporting nested dataframes in polars (https://biocpy.github.io/tutorial/chapters/representations/biocframe.html#advantages-of-biocframe), may be the way to approach this is to flatten and then convert to pandas or polars.

**Comment by jkanche** [comment]
v.0.5.11 should be published soon and helps interop between BiocFrame and Polars. Let me know if you run into any issues.
