### ISSUE TITLE
The "DataFrame" type hint does not work as is

### ISSUE THREAD

**Issue by DiDeoxy** [BiocPy/BiocFrame#32]
https://github.com/BiocPy/BiocFrame/blob/a817d93162ff3512746c3d1426978444cf1f370f/src/biocframe/io/from_pandas.py#L8
https://github.com/BiocPy/BiocFrame/blob/0e9fd418bcb9f70458e9ae392e52f264cb3f873e/src/biocframe/BiocFrame.py#L627

You need to import DataFrame from pandas to make this work. If you don't want it as a dependency then wrap the import in a try block. Can't import or export to pandas if it is not installed.

**Comment by jkanche** [comment]
that is exactly why
> If you don't want it as a dependency

I guess I could do that
