### ISSUE TITLE
pandas is not quite optional as `to_pandas()` has `DataFrame` as a type hint

### ISSUE THREAD

**Issue by LTLA** [BiocPy/BiocFrame#39]
https://github.com/BiocPy/BiocFrame/blob/daca714cd9b053378488d522fff4d5e61c8f9400/src/biocframe/BiocFrame.py#L652

This blows up CI that doesn't also install pandas, e.g., https://github.com/ArtifactDB/dolomite-base/actions/runs/6270387862/job/17028263635.

Probably just kill the type hint... what else could a user expect from a `to_pandas()` method, anyway?

**Comment by jkanche** [comment]
guess that was stupid, but it was suggested by someone, let me fix that
