### ISSUE TITLE
Either have `len()` be the number of columns, or rename `mcols()`

### ISSUE THREAD

**Issue by LTLA** [BiocPy/BiocFrame#68]
The `BiocFrame` doesn't technically follow Bioconductor semantics anymore in this regard. This is because we set `len()` to be the number of rows, but `mcols()` has number of rows equal to the number of columns in the `BiocFrame`.

The semantics around `mcols()` dictate that it has number of rows equal to the length of the object. In Bioconductor, the "length" of a `DataFrame` is equal to the number of columns, so that works out. Here, our `len()` is the number of rows, so the expectation around the `mcols()` doesn't hold anymore.

There are several solutions. 

1. Change the name of `mcols()` to something like `column_data()`, which is consistent with the treatment of other 2-dimensional objects like `SummarizedExperiment`. This frees us from the `mcols()` expectation.
2. Change `len()` so that it reports the number of columns. This is what Bioconductor does, because their `DataFrame` is basically a `List` of columns. Whether this is a good change is debatable, though users should probably be using `.shape` anyway.

**Comment by jkanche** [comment]
may be both?

**Comment by LTLA** [comment]
Contributing to this decision: what would `list(<BiocFrame>)` return? A list of columns? Or a list of row-based records?
