### ISSUE TITLE
add index alias for compatability with pandas

### ISSUE THREAD

**Issue by keviny2** [BiocPy/BiocFrame#9]

**Comment by keviny2** [comment]
want to access `rowNames` and `colNames` using `index` and `columns` properties like a pandas DataFrame

**Comment by jkanche** [comment]
sure would be similar to this section - https://github.com/BiocPy/BiocFrame/blob/master/src/biocframe/BiocFrame.py#L608

**Comment by keviny2** [comment]
looks like `columns` is already implemented. i'll just add `index`

**Comment by keviny2** [comment]
closed: https://github.com/BiocPy/BiocFrame/pull/10
